name: autorelease

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  autorelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: mise run install
      - run: mise run codegen
      - name: Create PR if differences exist
        if: github.event_name == 'push'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"

            BRANCH_NAME="chore/codegen"
            git checkout -b "$BRANCH_NAME"

            git add .
            git commit -m "chore: update generated code"
            git push origin "$BRANCH_NAME" --force

            gh pr create \
              --title "chore: update generated code" \
              --body "Automated PR to update generated code." \
              --base "${{ github.ref_name }}" \
              --head "$BRANCH_NAME" || echo "PR already exists, updated branch."
          fi
      - run: mise run ci
      - if: github.event_name == 'workflow_dispatch'
        name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v$(date +%Y.%m.%d-%H%M%S)" --generate-notes
